namespace Baytology.Application.Features.Properties.Dtos;

public record PropertyDto(
    Guid Id,
    string AgentUserId,
    string Title,
    string? Description,
    string PropertyType,
    string ListingType,
    decimal Price,
    decimal Area,
    int Bedrooms,
    int Bathrooms,
    int? Floor,
    int? TotalFloors,
    string? AddressLine,
    string? City,
    string? District,
    string? ZipCode,
    decimal? Latitude,
    decimal? Longitude,
    string Status,
    bool IsFeatured,
    DateTimeOffset CreatedOnUtc,
    List<PropertyImageDto>? Images,
    PropertyAmenityDto? Amenity,
    AgentSummaryDto? Agent);
